name: Call Private Workflow

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Private Workflow via API
        run: |
          curl --location 'https://api.github.com/repos/MohamedAbdelrehem/test-workflow/actions/workflows/main.yml/dispatches' \
          --header 'Accept: application/vnd.github+json' \
          --header "Authorization: Bearer ${{ secrets.WORKFLOWTOKEN }}" \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --header 'Content-Type: application/json' \
          --data '{"ref":"master"}'
